FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir rag
RUN mkdir rss_web_scraping

COPY rag/connection.py rag/
COPY rag/embedding.py rag/
COPY rag/chunking.py rag/
COPY rag/vector_store.py rag/

COPY rss_web_scraping/extract_content.py rss_web_scraping/

COPY rss_pipeline.py .

CMD ["rss_pipeline.main"]