FROM python:3.10-slim

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY chatbot.py .
COPY db_logic.py .
COPY history_dashboard.py .
COPY streamlit_functions.py .
COPY loading_animation.py .
COPY about_us.py .
COPY style.css .
COPY source_rankings.py .
COPY logo.png .

CMD streamlit run chatbot.py --server.port 8501