FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY retrieval.py .
COPY connection.py .
COPY main.py .

CMD ["main.main"]