FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY cluster.py .
COPY connection.py .
COPY embedding.py .

CMD ["cluster.main"]